# Generated by Django 3.1 on 2020-08-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateField()),
                ('text', models.CharField(max_length=200)),
                ('completed', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
