# Generated by Django 3.1.4 on 2020-12-08 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200827_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='added_date',
        ),
    ]
